/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.perm.v.infomaximum;

import ru.perm.v.infomaximum.data.Product;
import ru.perm.v.infomaximum.data.Report;
import ru.perm.v.infomaximum.parser.jsonreader.ProductJsonReader;
import ru.perm.v.infomaximum.parser.jsonreader.StatCreatorByListProducts;
import ru.perm.v.infomaximum.data.StatData;

import java.io.FileNotFoundException;
import java.util.List;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        System.out.println("Enter name file (JSON/CSV):");
        Scanner scanner = new Scanner(System.in);
        String filename = scanner.nextLine();
        if (filename.equals("exit")) {
            return;
        }
        System.out.println("Enter method parse:\n 1) with create Product\n 2) calc by word in json file (\"weight\",...):");
        String method = scanner.nextLine();
        if (method.equals("1")) {
            createStatWithCreateListProducts(filename);
        }
        if (method.equals("2")) {
            createStatByCalcWord(filename);
        }
    }

    /**
     * Получение статистики через выборку строк
     * @param filename файл с данными
     */
    private static void createStatByCalcWord(String filename) {
    }

    /**
     * Получение статистики с созданием списка Product
     *
     * @param filename файл с данными
     */
    private static void createStatWithCreateListProducts(String filename) {
        ProductJsonReader reader = new ProductJsonReader();
        try {
            List<Product> products = reader.readFromFile(filename);

            StatCreatorByListProducts statCreator = new StatCreatorByListProducts();

            StatData statData = new StatData();
            statData.setDuplicates(statCreator.getDuplicatesByGrpAndType(products));
            statData.setSumWegthByGroup(statCreator.getSumWegthByGroup(products));
            statData.setMinWeight(statCreator.getMinWeight(products));
            statData.setMaxWeight(statCreator.getMaxWeight(products));

            Report report = new Report(statData);
            report.print();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}
